name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          docker build . --file Dockerfile --tag registry.cn-hongkong.aliyuncs.com/littledian/tools-server:latest \
          && docker tag registry.cn-hongkong.aliyuncs.com/littledian/tools-server:latest registry.cn-hongkong.aliyuncs.com/littledian/tools-server:${{ steps.date.outputs.date }} \
          && docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }} registry.cn-hongkong.aliyuncs.com \
          && docker push registry.cn-hongkong.aliyuncs.com/littledian/tools-server:latest \
          && docker push registry.cn-hongkong.aliyuncs.com/littledian/tools-server:${{ steps.date.outputs.date }}
